### ISSUE TITLE
EOF: Don't copy type section

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#1003]
We unnecessarily copy the contents of the type section to `std::vector<EOFCodeType>`. It should be enough to read a type from the type section bytes on demand. E.g. `EOFCodeType get_type(size_t index)`.

**Comment by abloom22** [comment]
I'd like to work on this issue. Could you please assign it to me?

**Comment by chfast** [comment]
@aryeh-bloom this is assigned to you, are you working on this?

**Comment by aryeh-bloom** [comment]
@chfast yes sorry, I was out of town for most of last week and unable to get anything done at my computer

**Comment by elijahhampton** [comment]
@chfast I created a PR for this issue here: https://github.com/ethereum/evmone/pull/1034
