### ISSUE TITLE
Add more contracts to benchmarking suite

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#132]
- [ ] Add README with links to contracts source code
- [ ] https://blog.ricmoo.com/verifying-messages-in-solidity-50a94f82b2ca
- [ ] https://github.com/javgh/ed25519-solidity
- [ ] https://github.com/karalabe/snailtracer

**Comment by axic** [comment]
Upated snailtracer to Solidity 0.5.x: https://github.com/axic/snailtracer

You could also try https://github.com/axic/blake2-solidity with supporting the precompile. It has test case.s

**Comment by chfast** [comment]
> Upated snailtracer to Solidity 0.5.x: https://github.com/axic/snailtracer

Do you have some example inputs? This one is also using a lot of divisions, so not ideal for benchmarks...

> You could also try https://github.com/axic/blake2-solidity with supporting the precompile. It has test case.s

Do you have the native code for the precompile?

**Comment by chfast** [comment]
Closed because all of the mentioned codes use precompiles (except snailtracer https://github.com/ipsilon/evm-benchmarks/issues/8).
If you think we should reconsider any of these, create issue in https://github.com/ipsilon/evm-benchmarks.
