### ISSUE TITLE
evmone-unittests.exe silently stops executing when exception is thrown

### ISSUE THREAD

**Issue by halfalicious** [ethereum/evmone#147]
When an EVMOne test triggers an exception, evmone-unittests.exe will stop executing without logging an error or exception message so the user has no indication as to what caused the failure or that a test even failed. Note that this is also true if one runs evmone-unittests.exe in a debugger - the process will suddenly exit. It would be nice for both an exception message and call stack to be logged when an exception is detected during test execution.

**Comment by chfast** [comment]
What is the actual exception? What test?

**Comment by halfalicious** [comment]
> 
> 
> What is the actual exception? What test?

test = evm.empty (before PR #148 was merged)

So it looks like an exception wasn't being thrown but rather a function was being called (ucrtbased!_invalid_parameter -> ucrtbased!_invoke_watson) which terminated the program.
