### ISSUE TITLE
threading model

### ISSUE THREAD

**Issue by gcolvin** [ethereum/evmone#174]
README.md describes the current model, with a table of function pointers, as direct threading, but it is indirect.  Direct threading requires placing the address of the next opcode inline and jumping to it with no function call, typically using either assembly or GCC's address-of-label extension.  Pull request https://github.com/ethereum/evmone/pull/11 from @zac-williamson implements direct threading.

**Comment by chfast** [comment]
You are probably right, however I've found an article that referred to this table as DTT - direct threading table.

**Comment by mratsim** [comment]
I agree with @gcolvin. That would fit the [research papers](https://github.com/status-im/nimbus/wiki/Interpreter-optimization-resources) I've gathered, especially this one on [RealityForge](https://realityforge.org/code/virtual-machines/2011/05/19/interpreters.html).

**Comment by chfast** [comment]
Ok, see https://github.com/ethereum/evmone/pull/182.

Anyway, this one is probably the slowest.

**Comment by chfast** [comment]
After all these years, I'm finally getting threaded code support: https://github.com/ethereum/evmone/pull/495.
