### ISSUE TITLE
Add 32-bit support

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#192]
- [x] Add 32-bit build to CircleCI. (Example how to do it in other project: https://github.com/ethereum/evmc/blob/master/circle.yml#L149-L158)
- [x] Fix build issues / compiler warnings.
- [x] Test and fix the 32-bit binaries.

**Comment by hrishikeshSuresh** [comment]
I would like to work on this issue, if it hasn't been already assigned/done.

**Comment by chfast** [comment]
> I would like to work on this issue, if it hasn't been already assigned/done.

It's yours.

**Comment by chfast** [comment]
Thank you!
