### ISSUE TITLE
AdjustTime support

### ISSUE THREAD

**Issue by Pet3ris** [ethereum/evmone#194]
Hi There,

Does EVM One support the geth equivalent of `AdjustTime(duration time.Duration)` at this point? Conscious it's not part of the RPC spec and probably not the client-evm spec so answer may be no, but useful feature nonetheless!

**Comment by chfast** [comment]
Hi @Pet3ris,

This is rather out-of-scope when EVM is considered. However, with evmone implementing [EVMC](https://github.com/ethereum/evmc) API, it is very easy to provide any timestamp you like. Simply, EVM does not care about the value at all.

**Comment by Pet3ris** [comment]
@chfast - makes sense, thank you.
