### ISSUE TITLE
Reject code bigger than 0x6000

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#205]

**Comment by chfast** [comment]
I realized this is an issue for the create transaction, where the code size (transaction input) is only limited by the current gas limit — it can be > 600k for 10M block gas limit and transaction input byte cost of 16.

**Comment by axic** [comment]
@chfast wasn't this fully implemented?

**Comment by chfast** [comment]
No, as this cannot be implemented. But the related issue is fixed.
