### ISSUE TITLE
op_exp needs to have a shortcut for 2^e

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ethereum/evmone#231]
There are a lot of contracts on the Ethereum mainnet that were compiled with Solidity prior to the shifting operations were available. For those, exponentiation `2^160` is used to emulate `1<<160`. Measurements performed on turbo-geth confirm this. Since we are planning to integrate evmone into turbo-geth, and we have already implemented this shortcut (https://github.com/ledgerwatch/turbo-geth/pull/505), it would be good to maintain that in evmone.

**Comment by axic** [comment]
I think it would make sense considering an EIP for this, otherwise we are introducing yet another imbalance to "costs".

**Comment by AlexeyAkhunov** [comment]
I disagree with the notion that every performance improvement needs to lead to the decreasing gas cost. The other way around - yes
