### ISSUE TITLE
geth EVMC ABI Version Compatibility?

### ISSUE THREAD

**Issue by xanderdunn** [ethereum/evmone#391]
I'm on Ubuntu 18.04 with the release build 0.8.2 of evmone. I'm trying to use it as an external evm with geth to improve the performance of testing contracts locally.

The README recommends using [ewasm/go-ethereum](https://github.com/ewasm/go-ethereum/releases)'s geth binary, which hasn't been updated in over 2 years and appears to implement the EVMC ABI version 6, which is not compatible with evmone's release EVMC ABI version 9. 

I also tried the [etclabscore/core-geth](https://github.com/etclabscore/core-geth) latest geth binary, which [supports EVMC ABI version 7](https://etclabscore.github.io/core-geth/core/evmc/). Again, not compatible with latest evmone. 

Is there a version of geth somewhere that is compatible with evmone? If not, what is evmone's typical use case / how is evmone typically interacted with?

Thanks!

**Comment by chfast** [comment]
The evmone is typically used from C++ nowadays. The EVMC support in geth is not maintained because of lack of maintainers. Technically nothing prevents having the latest EVMC ABI support in geth.

**Comment by xanderdunn** [comment]
Thanks, is there an example C++ project somewhere that deploys contracts to evmone and calls functions on them?

**Comment by chfast** [comment]
This is how Solidity is using it for testing:
https://github.com/ethereum/solidity/blob/develop/test/EVMHost.cpp

This is Silkworm (C++ Ethereum client implementation) using evmone as the EVM implementation:
https://github.com/torquem-ch/silkworm/blob/master/core/silkworm/execution/evm.cpp

**Comment by xanderdunn** [comment]
Perfect, thanks. This is what I needed. The README might be updated to note the geth EVMC compatibility, but this is all I needed.

**Comment by chfast** [comment]
If you will use evmone in Go or any other language please come back to us with any results.
