### ISSUE TITLE
cannot work on bsc chain

### ISSUE THREAD

**Issue by byhashdong** [ethereum/evmone#392]
Just porting evmc on geth fork for bsc chain. When enable evmone, get errors as below:

```
ERROR[10-30|01:27:30.073]
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}

Number: 12201370
Hash: 0xf76832aa7437e6e723b59a8a4db3386e65c606428c187b25d19c24e27cfb5591
         0: cumulative: 256523 gas: 256523 contract: 0x0000000000000000000000000000000000000000 status: 0 tx: 0x21833916107fe9505894c8759abe755216fb655cc9ce029ec760dba715ad1b28 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state: 

```

**Comment by axic** [comment]
> ```
> Ramanujan: 0, Niels: 0
> ```

This suggests there are two more protocol updates on BSC called Ramanujan and Niels. If they require changes to evmone, they are certainly not implemented.

If you can provide links to clear technical documentation what those updates do, then we could give better feedback on feasibility.

**Comment by byhashdong** [comment]
@axic Thanks for you reply very much! 
Just checked Ramanujan and Niels, they are not related to gas. 
And I just found an case as below,  with evmone the gasUsed is low then bsc embedded EVM Interpreter.

https://bscscan.com/tx/0x94e623d6cc6840f3560a29e375d55860d7d12fe8e4f77ad6df84d869367d4e1e

**Comment by sjl623** [comment]
Hey, I meet the same problem. The key problem is that the gas price calculated by evmone is not equal to the one by GO implement, which leads to the consensus protocol can not accept the last transaction in a block. The last transaction in a block is always sent by validator to calculate the mining income:)

**Comment by chfast** [comment]
The reference implementation probably made some changes which are not implemented/configured here.
