### ISSUE TITLE
Implement stack space as uninitialized memory

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#403]
Currently the EVM stack space is provided by `uint256[256]`. This is wasteful because the whole space must be zero-initialized.
Moreover, we are reusing stack space for multiple executions therefore the stack space is dirty in some cases.

This can be implemented with `std::aligned_storage`. The [reference](https://en.cppreference.com/w/cpp/types/aligned_storage) has an example how to implement "static vector".

**Comment by priteshvermaa** [comment]
Hi @chfast,  I would like to contribute on to this issue.

**Comment by chfast** [comment]
Go ahead, @priteshvermaa.

**Comment by chfast** [comment]
The `std::aligned_storage` has been deprecated.

**Comment by axic** [comment]
@chfast so close this?

**Comment by chfast** [comment]
I plan to change how stack space is allocated, so this is related and I can close it then.
