### ISSUE TITLE
call / create opcodes appears to not `release` the `result`. (memory leak)

### ISSUE THREAD

**Issue by skylerqpq** [ethereum/evmone#417]
https://github.com/ethereum/evmone/blob/0c1685e17e38f092fd24b101e7a1c47b4da0f14b/lib/evmone/instructions_calls.cpp#L93-L102

https://github.com/ethereum/evmone/blob/0c1685e17e38f092fd24b101e7a1c47b4da0f14b/lib/evmone/instructions_calls.cpp#L161-L168

**Comment by chfast** [comment]
Hi @skylerqpq,

evmone is using EVMC C++ API and in this case the `result` is of type `evmc::result` which is a C++ RAII type responsible to release the result when going out of scope.

See
- https://evmc.ethereum.org/classevmc_1_1result.html
- https://github.com/ethereum/evmc/blob/master/include/evmc/evmc.hpp#L393-L398

**Comment by skylerqpq** [comment]
Ah, I thought I was missing something there, I checked the cpp api, just, the wrong part, heh.
