### ISSUE TITLE
loading model (multiple evms?), perf questions 

### ISSUE THREAD

**Issue by fxfactorial** [ethereum/evmone#444]
thanks for this project, 

1. so I managed to get evmone running as a geth plugin but i see that it uses DLL_OPEN for the `.so`, since I'm using it in the golang context, does that mean I can only load up the dll once? and effectively only have 1 evmone backed evm? if I have the same .so named multiple ways, then effectively I'd have multiple evmone evms correct? (Assuming the once loaded per file name constraint) 

2. no doubt the evmone is faster at push, pops than say the geth evm. but say given the context of using the go bindings, it seems the the overhead of cgocalls probably outweighs the speed benefits + some wrapping/unwrapping + .GetState/.SetState is anyway limited by backing data structures of db, etc. That said, I'm wondering about what could be some ways to maximizie runtime performance for the context of using libevm as a plugin

**Comment by chfast** [comment]
> 1. so I managed to get evmone running as a geth plugin but i see that it uses DLL_OPEN for the `.so`, since I'm using it in the golang context, does that mean I can only load up the dll once? and effectively only have 1 evmone backed evm? if I have the same .so named multiple ways, then effectively I'd have multiple evmone evms correct? (Assuming the once loaded per file name constraint)

You should load DLL once. Then you can create a VM instance multiple times with different configurations. Although, there is not so many configuration options, mostly you can select one of interpreters Advanced (`O=2`) or Baseline (`O=0`). Also the Go bindings are do both steps in single go (https://github.com/ethereum/evmc/blob/master/bindings/go/evmc/evmc.go#L120).

Once you have the VM instance you can execute multiple messages concurrently or subsequently. You only need to destroy the VM instance when you exit program.

> 2\. no doubt the evmone is faster at push, pops than say the geth evm. but say given the context of using the go bindings, it seems the the overhead of cgocalls probably outweighs the speed benefits + some wrapping/unwrapping + .GetState/.SetState is anyway limited by backing data structures of db, etc. That said, I'm wondering about what could be some ways to maximizie runtime performance for the context of using libevm as a plugin

Yes, this is known limitation especially for interfacing with Go. Maybe someone very familiar with cgo can improve situation a bit.

The high-level solution may be to move the API boundary up: at or above the transaction execution (currently EVMC API executes individual messages) and have some kind of State cache in EVM (so it should call Host only to load data from database but not data which was loaded recently).
