### ISSUE TITLE
Change from evmone::ExecutionState stack to evmone::advanced::Stack 

### ISSUE THREAD

**Issue by enriavil1** [ethereum/evmone#459]
After upgrading evmone I noticed that  evmone::ExecutionState doesn't contain a stack, but instead it only contains the StackSpace. I tried initiliazing and evmone::advanced::Stack using the StackSpace `bottom()`, but the evmone::advanced::Stack keeps a size of zero. After looking at the code it makes sense why it keeps a size of zero, but couldn't find a way to exchange my previous usage of the stack inside of ExecutionState  to the one I have with the variable `evmone::advanced::Stack`. To be more precise I am implementing the function `on_instruction_start` which takes in a `evmone::ExecutionState`.

**Comment by chfast** [comment]
Is this resolved?

**Comment by enriavil1** [comment]
Yes, it took me a second a little but understood how to adapt to the change after a little. Thank you
