### ISSUE TITLE
Performance : switch to gmp from intx 

### ISSUE THREAD

**Issue by ytrezq** [ethereum/evmone#486]
I know this should come with benchmarks but gmp is well known for the best performance arbitrary precision arithmetics on Integers. For small Integers, it come with multiple vectorized versions written directly in assembly (example neon on arm and both sse and avx on Intel).

**Comment by chfast** [comment]
intx is faster.

**Comment by ytrezq** [comment]
@chfast intx isn’t written in assembly at all.

**Comment by chfast** [comment]
If you can show a case where GMP is faster (in the EVM implementation context) I will reconsider.
