### ISSUE TITLE
Tracer.notify_execution_start is called with truncated code

### ISSUE THREAD

**Issue by yperbasis** [ethereum/evmone#528]
`code` at https://github.com/ethereum/evmone/blob/master/lib/evmone/baseline.cpp#L330 is just a pointer, so for values like  `0x602a6000556101c960015560068060166000396000f3600035600055` (containing 0 bytes) `notify_execution_start` only sees `0x602a60`. This leads to a regression in Silkworm's TEST_CASE("Tracing smart contract with storage").

[v0.9.1](https://github.com/ethereum/evmone/releases/tag/v0.9.1) does not suffer from this issue.

**Comment by chfast** [comment]
The problem is the tracer takes `bytes_view` but now pointer is provided and converted to `bytes_view` which stops on the first null byte. We should provide the code length to the `bytes_view` constructor: `{code, code_size}`.
