### ISSUE TITLE
Restrict DUPN and SWAPN to EOF only

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#538]
The `DUPN` and `SWAPN` instructions implemented in #529 are enabled in Cancun in both EOF and legacy code. Limit the availability to EOF only.

**Comment by pdobacz** [comment]
> The `DUPN` and `SWAPN` instructions implemented in #529 are enabled in Cancun in both EOF and legacy code. Limit the availability to EOF only.

It seems they already have been already restricted to EOF (EVMC_PRAGUE) see https://github.com/ethereum/evmone/blob/5d8657380596d6ec9d81d6b08de381ff13c3cfa0/lib/evmone/instructions_traits.hpp#L390C14-L391.

I'll close this, pls reopen if anything else needs to be done here.

**Comment by gumb0** [comment]
Still need to undefine them in https://github.com/ethereum/evmone/blob/79eb777e0480a0d8e05f96dc76972894a08a2367/lib/evmone/baseline_instruction_table.cpp#L25
