### ISSUE TITLE
EOF validation in tools / tests

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#585]
When an execution code is taken from external source (e.g. CLI or JSON tests) we should perform EOF validation to keep the EOF guarantee of deployed code being always valid.

Places where it's needed:

- [ ] CLI EVM execution (`evmc run`?)
- [x] JSON state test loader or runner https://github.com/ethereum/evmone/pull/593

**Comment by gumb0** [comment]
JSON tests should validate it before being filled, not sure we need to do it another time for them.

**Comment by chfast** [comment]
> JSON tests should validate it before being filled, not sure we need to do it another time for them.

This is just sanity check to detect broken tests. Otherwise you will see some crashes.

**Comment by pdobacz** [comment]
Is this still relevant? Also, to what extent exactly does https://github.com/ethereum/evmone/pull/593 fix this?
