### ISSUE TITLE
Investigate goevmlab fuzzing failure

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#697]
Please check the test case https://gist.github.com/namiloh/daa1f238021dc57873964dd2c41bebd6.

_Originally posted by @namiloh in https://github.com/ethereum/evmone/issues/692#issuecomment-1694336756_

**Comment by chfast** [comment]
The test itself seems invalid. evmone reports that the transaction is invalid because of "insufficient funds". The outcome is because evmone trusts the `"sender"` value and ignores `"secretKey"`. It looks that the test generator incorrectly sets the sender to a null address (it cannot match any secret key).

**Comment by holiman** [comment]
Fixed in goevmlab -- I lost "sender" when marshalling/unmarshalling a state-test. Fix: https://github.com/holiman/goevmlab/commit/7f729da4c9ae67afbe9d424d525bcd7c90c51f3b
