### ISSUE TITLE
libgmp-dev is a required package

### ISSUE THREAD

**Issue by winsvega** [ethereum/evmone#720]
cmake failed to install gmp package with hunter. 
```
CMake Error in build/_deps/silkpre-src/third_party/libff/libff/CMakeLists.txt:
  Imported target "GMP::gmp" includes non-existent path

    "GMP_INCLUDE_DIR-NOTFOUND"
```

solved by 
```
sudo apt install libgmp-dev
```

but need to add this to readme instructions

**Comment by pdobacz** [comment]
@winsvega It is mentioned as a requirement when silkpre is enabled, which seems to be the case here. It's at the very end of https://github.com/ethereum/evmone#precompiles, does this work for you?
