### ISSUE TITLE
Compute `CREATE` address without RLP library

### ISSUE THREAD

**Issue by chfast** [ethereum/evmone#783]
We want to decouple RLP library (mostly used in testing infrastructure and MPT hashing) from the core EVM state modifications. The `CREATE` address derivation is the only place where RLP is used. For this we only need to implement RLP encoding for `uint64`.

See the TODO comment at https://github.com/ethereum/evmone/blob/v0.11.0/test/state/host.cpp#L149.

**Comment by AbhinavMir** [comment]
@chfast Does the draft PR above look right? I looked at how Aleth used to [encode JSON objects](https://github.com/ethereum/aleth/blob/master/rlp/main.cpp#L430) and bounced off from there to create a `rlp_encode_uint64` function.

**Comment by elijahhampton** [comment]
Looks like the PR for this wasn't accepted and has gone stale. I can pick this up @chfast

**Comment by chfast** [comment]
Ok, give it a try. For the clarification: any JSON should not be involved.

**Comment by chfast** [comment]
I made a draft for it: #1055.
