### ISSUE TITLE
t8n should always assume a block logic

### ISSUE THREAD

**Issue by winsvega** [ethereum/evmone#822]
it is always assumed that t8n is executed in block mode. 
so all the block level operations are expected to be performed. 

beacon root contract call in the begining. 
mining reward at finalization

**Comment by chfast** [comment]
Can you provide example inputs?

**Comment by winsvega** [comment]
Here is an example of beacon root precompile sys call:
http://retesteth.ethdevops.io/temp/geth/default_Cancun_block1_0x23e6c9/
