### ISSUE TITLE
evmone t8n beacon root logic

### ISSUE THREAD

**Issue by winsvega** [ethereum/evmone#832]
So the beacon root on Cancun logic with t8n is following:

at the begining of execution on Cancun and higher - call the beacon contract 
a) can call it via system call and put the beacon hash information into storage (bytecode do this)
b) can manually write storage cells without executing it's bytecode

in both options, if there were no beacon contract in pre state, the result would be empty account that gets deleted. 
so no changes.  but if there was an account, the storages are being set. 

currently evmone t8n does not perform beacon logic. we agree that t8n does not diff state or bc test is being generated, so it always generate a block.  meaning that account touch is performed, mining reward, beacon logic.  so far we can still generate 'state tests only' version by setting mining reward to 0, and beacon root to not present in pre state.

**Comment by chfast** [comment]
The `evmone-t8n` must invoke `system_call()` the same as `evmone-blockchaintest` does.

**Comment by chfast** [comment]
Can you provide example inputs?
