### ISSUE TITLE
Support generation of fillers from state transition tests

### ISSUE THREAD

**Issue by pdobacz** [ethereum/evmone#835]

**Comment by pdobacz** [comment]
@gumb0 To be sure, this is about transforming (or enhancing) `state_transition::export_state_test` to be able to output files like `tests/src/EIPTestsFiller/StateTests/stEOF/stEIP3540/EOF1_ExecutionFiller.yml`, which later fed to `retesteth` would produce the same (equivalent?) .json test files as we currently produce?

**Comment by gumb0** [comment]
Correct.

(It can also be json files with the format equivalent to those ymls, if we don't want to bring in extra yaml dependency into evmone. But yml of course would be better for human readability)

**Comment by chfast** [comment]
You can also output YML by hand. The `std::format` can be useful here, but check availability.

**Comment by pdobacz** [comment]
Do we still want to do this in light of [potential deprecation of retesteth](https://github.com/ethereum/tests/pull/1358#issuecomment-2018128383) ?
