### ISSUE TITLE
question: eof stack validation, CALLF overflow check

### ISSUE THREAD

**Issue by rakita** [ethereum/evmone#843]
I have a question, not sure this part of code is correct:

https://github.com/ethereum/evmone/blob/97ff9aa1bf9527b8b4ddb729b74dfbad993abfe5/lib/evmone/eof.cpp#L389-L393

Here we compare the:
`stack_height.max + code_types[fid].max_stack_height - code_types[fid].inputs`

But shouldn't this be:
`stack_height.max + code_types[fid].max_stack_height - instr::traits[opcode].stack_height_required`

We should decrement by number items of CALLF not number of inputs of code section.

**Comment by rakita** [comment]
hm in CALLF case  `instr::traits[opcode].stack_height_required` would be `0`

**Comment by pdobacz** [comment]
It seems to be as specced out. And indeed `instr::traits[opcode].stack_height_required` is 0 for CALLF, as it doesn't consume any stack arguments itself. 

The condition here checks if the callee section won't exceed the stack limit, assuming it starts from its `inputs` and there's a `max stack height` reached, as declared in the types section.

**Comment by rakita** [comment]
> The condition here checks if the callee section won't exceed the stack limit, assuming it starts from its `inputs` and there's a `max stack height` reached, as declared in the types section.

Okay, I think I got it.  `- code_types[fid].inputs` was confusing for me, but it means that those inputs are already accounted for in the curent `stack_height.max`, that is why we need to subtract them.
