### ISSUE TITLE
check thath evmone-statetest parse multi test jsons

### ISSUE THREAD

**Issue by winsvega** [ethereum/evmone#862]
Pyspec introduced new state test format

Before each test.json had only 1 state test vector like this:
```
{
    "testName" : {
        ..TEST..
    }
}
```

Now it looks like a blockchain
```
{
    "testName" : {
        ..TEST..
    },
    "testName_2" : {
        ..TEST..
    },
    "testName_3" : {
        ..TEST..
    }
}
```

Many state vectors in one state test .json file.
I have a felling that evmone-statetest tool is not parsing multi vectors, just taking the first one. could you please check?

**Comment by chfast** [comment]
In `evmone-statetest` we only load (and execute) the first test case (https://github.com/ethereum/evmone/blob/master/test/statetest/statetest_loader.cpp#L420).
