### ISSUE TITLE
evmone-eofparse does not return an error code

### ISSUE THREAD

**Issue by winsvega** [ethereum/evmone#872]
evmone-eofparse return 0 no-error code even on errors. 
it better to return an error code and print the error to stderr. 

also when calling it without args, it just hangs without printing any message (like a help message)

**Comment by chfast** [comment]
The tool was implemented for specific needs of the EOF validation fuzzer. It takes each line of the input file as a separate EOF and outputs the error to the stdout. Maybe this can be changed but you would need to consult it with the other project.

I can return the number of errors though...
