### ISSUE TITLE
evmone-eofparse need to print version and error

### ISSUE THREAD

**Issue by winsvega** [ethereum/evmone#877]
currently evmone-eofparse is witing for pipe input to be used like this

```
echo $code | evmone-eofparse
```

but it should also return help if called without input or args something like this: 
```
$evmone-eofparse
evmone eof verification tool version: xxx
args: 
   --code "hex"    eof code to verify
```

same with `$evmone-eofparse -v`

also in case of the code is not OK, it should return an error code and print to stderror 
currently the return code is 0, and all output is in stdout

**Comment by chfast** [comment]
It is a bit hard to add CLI features to this tool and also keep it compatible with other implementations and tools when there is no any spec.

@MariusVanDerWijden, is there the original fuzzer anywhere around?
