### ISSUE TITLE
Undo silencing of a failing EEST test

### ISSUE THREAD

**Issue by pdobacz** [ethereum/evmone#939]
Undo https://github.com/ethereum/evmone/pull/937, once --initcode flag is working and we can use it to fix the test.

EDIT: unsilencing might be possible earlier than we thought, because the failing cases were removed from that test: https://github.com/ethereum/execution-spec-tests/pull/650/commits/09a917eb2b3b6d971d9bd105b52a35c10b120c11

**Comment by gumb0** [comment]
This can be closed I think, there's no silencing on master.

**Comment by pdobacz** [comment]
yea, gh projects automation didn't close :shrug:
