### ISSUE TITLE
Upsetting news about efficient gas calculation algorithm (used in advanced mode)

### ISSUE THREAD

**Issue by ioterw** [ethereum/evmone#952]
Recently was learning about evmone internals.

And found out about this algorithm:
https://github.com/ethereum/evmone/blob/3bab1de1ac5cb58aacc0bd6cc893737a1e216f2c/docs/efficient_gas_calculation_algorithm.md

After testing evmone and reading the code it looks like it is working the same way it is described in the doc.

Maybe it was correct before, but right now it is wrong and leads to consensus violation.

Why?

Let's assume we have contract with such code:
```solidity
push0
extcodesize
pop
pop
stop
```

- It is seen that it produces one basic block
- Also it is visible for algorithm that it will stack underflow
- Therefore, it will not be executed and instantly reverted (according to the algoritm)
- This behavior is wrong because extcodesize MUST be executed because it will `warm` the 0 address, and next calls to this address will have reduced cost (despite call was reverted)

Possible ways to fix:
- put ext*/sload/sstore instructions in separate blocks
- use algorithm only in the first layer of call depth
- disable algorithm

Made a small test of validity of execution (tx should be runned with empty access list)
```solidity
// validates that gas cost is big for extcodesize when it is not warm
contract M1 {
    constructor() {
        uint gas_before = gasleft();
        uint lol;
        assembly {
            lol := extcodesize(0)
        }
        uint gas_after = gasleft();
        require(gas_before - gas_after >= 1000);
        assembly {
            stop()
        }
    }
}
// validates that gas cost is small for extcodesize when it is warm after reverted execution
contract M2 {
    constructor() {
        address warm = address(new Warm());
        (bool success,) = warm.call{gas:3000}("");
        require(!success);
        uint gas_before = gasleft();
        uint lol;
        assembly {
            lol := extcodesize(0)
        }
        uint gas_after = gasleft();
        require(gas_before - gas_after < 1000);
        assembly {
            stop()
        }
    }
}
contract Warm {
    constructor() payable {
        bytes memory code = hex"5f3b505000";
        assembly {
            return(160, mload(code))
        }
    }
}
```

**Comment by BoogerWooger** [comment]
Is it:

normal EVM:
 - "fails iside the CALL(stack uderflow) and then executes EXTCODESIZE for 300 gas"
EVMOne (with basic block revert optimization):
- "fails iside the CALL(stack uderflow) and then executes EXTCODESIZE for 2700 gas"

?

**Comment by ioterw** [comment]
@BoogerWooger right 👍

**Comment by chfast** [comment]
From the [EIP-2929: Gas cost increases for state access opcodes](https://eips.ethereum.org/EIPS/eip-2929):

> When executing a transaction, maintain a set `accessed_addresses: Set[Address]` and `accessed_storage_keys: Set[Tuple[Address, Bytes32]]` . 
> 
> The sets are transaction-context-wide, implemented identically to other transaction-scoped constructs such as the self-destruct-list and global `refund` counter. In particular, **if a scope reverts, the access lists should be in the state they were in before that scope was entered**. 

In other words, your understanding that the `EXTCODESIZE` to address next after the reverted call will be cheaper seems to be wrong. Can you provide the bytecode and a trace of execution of your example?

**Comment by ioterw** [comment]
Thx for reply. Indeed I got some strange misconseption (not sure how came I). Closing the issue. Sorry for a nonsense report.
